from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('ad8400', src, depend = ['PKG_USING_AD8400'], CPPPATH = CPPPATH)

Return('group')
